import "./globals.css";
import {Nunito, Nunito_Sans} from 'next/font/google' 
export const metadata = {
  title: "Mafkins Robotics",
  description: "Generated by create next app",
};

//specifying variable for font
const font= Nunito_Sans(
  {
    subsets: ['latin'],
    weight: ["200","300","400","500","600","700"],
    display: "swap"
  }
)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
